---
allowed_cache_instance_types:
  - cache.m5.large
  - cache.m5.xlarge
  - cache.m5.2xlarge
  - cache.m5.4xlarge
  - cache.m5.12xlarge
  - cache.m5.24xlarge
  - cache.m4.large
  - cache.m4.xlarge
  - cache.m4.2xlarge
  - cache.m4.4xlarge
  - cache.m4.10xlarge
  - cache.t3.micro
  - cache.t3.small
  - cache.t3.medium
allowed_db_instance_types:
  - db.t3.medium
  - db.t3.large
  - db.t4g.medium
  - db.t4g.large
  - db.r5.large
  - db.r5.xlarge
  - db.r5.2xlarge
  - db.r5.4xlarge
  - db.r5.8xlarge
  - db.r5.12xlarge
  - db.r5.16xlarge
  - db.r5.24xlarge
  - db.r6i.large
  - db.r6i.xlarge
  - db.r6i.2xlarge
  - db.r6i.4xlarge
  - db.r6i.8xlarge
  - db.r6i.12xlarge
  - db.r6i.16xlarge
  - db.r6i.24xlarge
  - db.r6i.32xlarge
  - db.r6g.large
  - db.r6g.xlarge
  - db.r6g.2xlarge
  - db.r6g.4xlarge
  - db.r6g.8xlarge
  - db.r6g.12xlarge
  - db.r6g.16xlarge
  - db.x2g.large
  - db.x2g.xlarge
  - db.x2g.2xlarge
  - db.x2g.4xlarge
  - db.x2g.8xlarge
  - db.x2g.12xlarge
  - db.x2g.16xlarge
allowed_instance_types:
  - c5.12xlarge
  - c5.18xlarge
  - c5.24xlarge
  - c5.2xlarge
  - c5.4xlarge
  - c5.9xlarge
  - c5.large
  - c5.metal
  - c5.xlarge
  - c5d.12xlarge
  - c5d.18xlarge
  - c5d.24xlarge
  - c5d.2xlarge
  - c5d.4xlarge
  - c5d.9xlarge
  - c5d.large
  - c5d.xlarge
  - m5.12xlarge
  - m5.16xlarge
  - m5.24xlarge
  - m5.2xlarge
  - m5.4xlarge
  - m5.8xlarge
  - m5.large
  - m5.metal
  - m5.xlarge
  - m5d.12xlarge
  - m5d.16xlarge
  - m5d.24xlarge
  - m5d.2xlarge
  - m5d.4xlarge
  - m5d.8xlarge
  - m5d.large
  - m5d.metal
  - m5d.xlarge
  - r5.12xlarge
  - r5.16xlarge
  - r5.24xlarge
  - r5.2xlarge
  - r5.4xlarge
  - r5.8xlarge
  - r5.large
  - r5.metal
  - r5.xlarge
  - r5d.12xlarge
  - r5d.16xlarge
  - r5d.24xlarge
  - r5d.2xlarge
  - r5d.4xlarge
  - r5d.8xlarge
  - r5d.large
  - r5d.metal
  - r5d.xlarge
  - t3.2xlarge
  - t3.large
  - t3.medium
  - t3.micro
  - t3.nano
  - t3.small
  - t3.xlarge
allowed_regions:
  - af-south-1
  - ap-east-1
  - ap-northeast-1
  - ap-northeast-2
  - ap-northeast-3
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ap-southeast-3
  - ca-central-1
  - eu-central-1
  - eu-central-2
  - eu-north-1
  - eu-south-1
  - eu-south-2
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - me-central-1
  - me-south-1
  - sa-east-1
  - us-east-2
  - us-west-1
  - us-west-2
