---
"Product ID": ""
"Product Code": ""
"Accessibility": "Public"
"SKU": "OE_PATTERNS_MASTODON"
"Software by": "Ordinary Experts"
"Title": "Ordinary Experts Mastodon Pattern"
"Short Description": "The Ordinary Experts Mastodon Pattern is a custom AMI + open-source AWS CloudFormation template that provisions a production-ready, AWS infrastructure solution for deploying Mastodon."
"Full Description": "The Ordinary Experts Mastodon Pattern is an open-source AWS CloudFormation template that offers an easy-to-install AWS infrastructure solution for quickly deploying Mastodon, using both AWS and Mastodon best practices.

Automatically configured to support auto-scaling through AWS Autoscaling Groups, this solution leverages an S3 bucket for user generated content between application servers. It also provisions an OpenSearch Service domain for search, and an ElastiCache Redis cluster for cache. It configures SES with Easy DKIM for emails, and configures Route53 with convenient DNS entries.

The template ensure multi-level security by incorporating AWS IAM for federated access to resources with least privilege and AWS managed keys and Secret Manager to manage secrets for encryption of data at rest and in transit.

We support multiple availability zones using an RDS Aurora Postgresql cluster and EC2 Auto Scaling Groups."
"Highlight1": "Production-ready Mastodon site, with search, email, and caching"
"Highlight2": "Integrated with AWS Certificate Manager for HTTPS support"
"Highlight3": "Logs in CloudWatch Logs, Remote access via Session Manager"
"Product Category1": "Application Stacks"
"Product Category2": "Media & Entertainment"
"Product Category3": "Content Management"
"Search Keywords": "mastodon, social, twitter"
"Resource1_Name": "Ordinary Experts Product Page"
"Resource1_URL": "https://ordinaryexperts.com/products/mastodon-pattern/"
"Resource2_Name": "Github Source Code and Documentation"
"Resource2_URL": "https://github.com/ordinaryexperts/aws-marketplace-oe-patterns-mastodon/tree/{{version}}"
"Resource3_Name": "Mastodon Homepage"
"Resource3_URL": "https://joinmastodon.org/"
"Image URL": "https://ordinaryexperts.com/img/products/mastodon-pattern/mastodon-product-logo.png"
"Product Video": "TODO"
"Support Offered": "TRUE"
"Support Information": "https://ordinaryexperts.com/products/mastodon-pattern/"
"Support Detail": "Email support offered with subscription."
"Refund and Cancelation Policy": "We do not currently support refunds, but you can cancel at any time."
"Type": "AMI"
"us-east-1 AMI ID": "{{ami}}" # final ami id
"AMI Virtualization Type": "HVM"
"Architecture": "x86_64"
"AFI": ""
"Operating System": "Ubuntu"
"Operating System Version": "20.04"
"Operating System Username": "ubuntu"
"PIOPS Total": ""
"AWS Services Required": "Amazon EC2, Amazon RDS, Amazon S3, Amazon CloudWatch, Amazon OpenSearch Service, Amazon ElastiCache, Amazon VPC, Amazon SecretsManager, Amazon IAM, Amazon SNS, Amazon CertificateManager, Amazon CloudFormation"
"3rd Party Software Included": "Mastodon, Ubuntu packages: curl git jq ntp unzip vim wget zip python-pip collectd ruby binutils git nginx AWS CloudFormation utilities, AWS CLI, AWS CloudWatch agent"
"Version Title": "{{version}}"
"Release Notes": "See GitHub project for release notes."
"Upgrade Instructions": "Re-run the stack to apply new infrastructure changes."
"Product Access Instructions": "Run the stack, providing a valid parameters. When the stack creation completes, go to the outputs of the stack and open url in the outputs in your browser. To access the application servers, find the EC2 instance in the AWS console and \"Connect\" using the Session Manager option. For more detailed instructions, see the GitHub project."
"Endpoint URL Protocol": "http/https"
"Endpoint URL Port": "80/443"
"Endpoint URL Relative URL": "/"
"Countries to include": ""
"Countries to exclude": ""
# EULA: https://docs.aws.amazon.com/marketplace/latest/userguide/standardized-license-terms.html
"End User License Agreement URL": "https://s3.amazonaws.com/EULA/Standard+Contract+for+AWS+Marketplace+2019-04-24.pdf"
# region availability fields are here, i.e. "me-south-1 Availability"
"Make available in all future U.S. regions": "FALSE"
"Make available in all future non-U.S. regions": "FALSE"
"Recommended Instance Type": "m5.xlarge"
"Make available for all future instance types": "FALSE"
# instance availability fields are here, i.e. "z1d.12xlarge Availability"
"Pricing Model": "Hourly_Annual"
"Product Tax Code": "A_GEN_NOTAX"
"BYOL URL": ""
"Free Trial Instance Count": "1"
"Free Trial Duration": "5"
# instance Hourly Price fields are here, i.e. "z1d.12xlarge Hourly Price"
"Monthly Price": ""
# instance Annual Price fields are here, i.e. "z1d.12xlarge Annual Price"
"Security Group Rule 1": ""
"Security Group Rule 2": ""
"Security Group Rule 3": ""
"Security Group Rule 4": ""
"Security Group Rule 5": ""
"Security Group Rule 6": ""
"Security Group Rule 7": ""
"Security Group Rule 8": ""
"Security Group Rule 9": ""
"Security Group Rule 10": ""
"Security Group Rule 11": ""
"Security Group Rule 12": ""
"FCP Category": ""
"FCP Unit": ""
"FCP Dimension1 Name": ""
"FCP Dimension1 Description": ""
"FCP Dimension1 Rate": ""
"FCP Dimension2 Name": ""
"FCP Dimension2 Description": ""
"FCP Dimension2 Rate": ""
"FCP Dimension3 Name": ""
"FCP Dimension3 Description": ""
"FCP Dimension3 Rate": ""
"FCP Dimension4 Name": ""
"FCP Dimension4 Description": ""
"FCP Dimension4 Rate": ""
"FCP Dimension5 Name": ""
"FCP Dimension5 Description": ""
"FCP Dimension5 Rate": ""
"FCP Dimension6 Name": ""
"FCP Dimension6 Description": ""
"FCP Dimension6 Rate": ""
"FCP Dimension7 Name": ""
"FCP Dimension7 Description": ""
"FCP Dimension7 Rate": ""
"FCP Dimension8 Name": ""
"FCP Dimension8 Description": ""
"FCP Dimension8 Rate": ""
"FCP Dimension9 Name": ""
"FCP Dimension9 Description": ""
"FCP Dimension9 Rate": ""
"FCP Dimension10 Name": ""
"FCP Dimension10 Description": ""
"FCP Dimension10 Rate": ""
"FCP Dimension11 Name": ""
"FCP Dimension11 Description": ""
"FCP Dimension11 Rate": ""
"FCP Dimension12 Name": ""
"FCP Dimension12 Description": ""
"FCP Dimension12 Rate": ""
"FCP Dimension13 Name": ""
"FCP Dimension13 Description": ""
"FCP Dimension13 Rate": ""
"FCP Dimension14 Name": ""
"FCP Dimension14 Description": ""
"FCP Dimension14 Rate": ""
"FCP Dimension15 Name": ""
"FCP Dimension15 Description": ""
"FCP Dimension15 Rate": ""
"FCP Dimension16 Name": ""
"FCP Dimension16 Description": ""
"FCP Dimension16 Rate": ""
"FCP Dimension17 Name": ""
"FCP Dimension17 Description": ""
"FCP Dimension17 Rate": ""
"FCP Dimension18 Name": ""
"FCP Dimension18 Description": ""
"FCP Dimension18 Rate": ""
"FCP Dimension19 Name": ""
"FCP Dimension19 Description": ""
"FCP Dimension19 Rate": ""
"FCP Dimension20 Name": ""
"FCP Dimension20 Description": ""
"FCP Dimension20 Rate": ""
"FCP Dimension21 Name": ""
"FCP Dimension21 Description": ""
"FCP Dimension21 Rate": ""
"FCP Dimension22 Name": ""
"FCP Dimension22 Description": ""
"FCP Dimension22 Rate": ""
"FCP Dimension23 Name": ""
"FCP Dimension23 Description": ""
"FCP Dimension23 Rate": ""
"FCP Dimension24 Name": ""
"FCP Dimension24 Description": ""
"FCP Dimension24 Rate": ""
"Clusters and AWS Resources Topology 1: Title": "Ordinary Experts Mastodon Pattern"
"Clusters and AWS Resources Topology 1: AWS Calculator Link": "https://calculator.aws/#/estimate?id=28e0721d09cea568f7e0551967dc6da246dbcf5d"
"Clusters and AWS Resources Topology 1: Short Description": "Ordinary Experts Mastodon Pattern AWS Architecture Diagram"
"Clusters and AWS Resources Topology 1: Long Description": "The Ordinary Experts Mastodon Patterns AWS Architecture Diagram shows the total flow of services from when the customer accesses the Mastodon application. The diagram shows the following AWS Services: Amazon Simple Storage System (Amazon S3), Amazon Elastic Compute Cloud (Amazon EC2), Amazon Virtual Public Cloud (Amazon VPC), Amazon Aurora Postgresql, Amazon Secrets Manager, Amazon OpenSearch Service, and Amazon ElastiCache."
"Clusters and AWS Resources Topology 1: CloudFormation Template URL": "https://ordinary-experts-aws-marketplace-pattern-artifacts.s3.amazonaws.com/mastodon/{{version}}/template.yaml"
"Clusters and AWS Resources Topology 1: Architecture Diagram URL": "https://ordinaryexperts.com/img/services/oe_mastodon_patterns_topology_diagram.png"
"Clusters and AWS Resources Topology 2: Title": ""
"Clusters and AWS Resources Topology 2: AWS Calculator Link": ""
"Clusters and AWS Resources Topology 2: Short Description": ""
"Clusters and AWS Resources Topology 2: Long Description": ""
"Clusters and AWS Resources Topology 2: CloudFormation Template URL": ""
"Clusters and AWS Resources Topology 2: Architecture Diagram URL": ""
"Clusters and AWS Resources Topology 3: Title": ""
"Clusters and AWS Resources Topology 3: AWS Calculator Link": ""
"Clusters and AWS Resources Topology 3: Short Description": ""
"Clusters and AWS Resources Topology 3: Long Description": ""
"Clusters and AWS Resources Topology 3: CloudFormation Template URL": ""
"Clusters and AWS Resources Topology 3: Architecture Diagram URL": ""
